export const users = [
    {
        firstName : 'lilly',
        secondName: 'flower',
        email:'lilly@gmail.com',
        password:'123123123',
    }
]

const category = [
  {
    Romance:9
  },
  {
    Musical:5
  },
  {
    Fantasy:7
  },
  {
    Adventure:6
  },
  {
    SciFi:7
  },
  {
    Comedy:7
  },
  {
    Horror:6
  },
  {
    Action:7
  },
  {
    Thriller:5
  },
  {
    Crime:1
  },
  {
    Drama:7
  },
  {
    Supernatural:1
  }

]

export const movies = [
    {
      name:'Purple Hearts',
      category:'Romance,Musical',
      description:'Cassie, a struggling singer-songwriter agrees to marry a troubled Marine, Luke for military benefits. The line between real and pretend begins to blur.',
      landscapeImg:['https://occ-0-2164-58.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABVh8Pv10J2DgR_4GDab5ojMiMb6hc2Jz0bYLJG9LBZnrB60DZXdR5HnvczDQrq05V6FIp9xdNDVxVm6yl2XvCgm657vcTv1ieXahyKMoUy9-D-xZRwxkDZbONobkWrl2qTQk.jpg?r=30b'],
      portraitImg:["https://cdn.cinematerial.com/p/297x/jqbp9olv/purple-hearts-movie-poster-md.jpg?v=1657648849"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/WTLgg8oRSBE?si=016kUqKJS0St4PzR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Elizabeth Allen Rosenbaum',
      cast:["Sofia Carson", "Nicholas Galitzine", "Chosen Jacobs"],
      retailers:[
        {
          name:'Netflix',
          price:199,
          link:'https://www.netflix.com/title/81043665'
        }
      ],
      price:199,
      release:2022,
      id:1,
      likes:12,
    },
    {
      name:'La La Land',
      category:' Musical,Romance',
      description:'When Sebastian, a pianist, and Mia, an actress, follow their passion and achieve success in their respective fields, they find themselves torn between their love for each other and their careers.',
      landscapeImg:["https://occ-0-2164-58.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABdqFAxos5onsFEEt5pL_0FKoC-_senAHrQxDaER0Iu4sPaNzJfKWprgJkq5nJZcwOS88l29lXvrENRX1E39YjGc5TLUHCEFxUGE.webp?r=1f6"],
      portraitImg:["https://www.belarte.co.uk/cdn/shop/products/LaLaLand.jpg?v=1622308522"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/0pdqf4P9MB8?si=XS-6v0sy2lWY2hvt" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Damien Chazelle',
      cast:["Ryan Gosling","Emma Stone","John Legend"],
      price:199,
      release:2016,
      id:2,
      likes:35,
    },
    {
      name:'Cinderella 2015',
      category:'Romance,Fantasy',
      description:"After her father's death, Ella is tormented by her venomous stepmother and stepsisters. Her life changes dramatically when a crown prince, who is smitten with her, invites her to a royal ball.",
      landscapeImg:["https://assets.change.org/photos/4/df/bv/iwdFbvAPtwZagIK-1600x900-noPad.jpg?1632165706"],
      portraitImg:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAeMliuKsIr4VA5QPpiLlW8yD7ZFdHwclB9TT4SJCktmXEkx9t"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/LfR8Su4ulX0?si=SCfDMZ_9g1TGMUDz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Kenneth Branagh',
      cast:["Cate Blanchett","Lily James","Richard Madden"],
      price:199,
      release:2015,
      id:3,
      likes:89,
    },
    {
      name:'Titanic',
      category:'Romance,Adventure',
      description:'Rose, who is being forced to marry a wealthy man, falls in love with Jack, a talented artist, aboard the unsinkable Titanic. Unfortunately, the ship hits an iceberg, endangering their lives.',
      landscapeImg:["https://rukminim1.flixcart.com/image/850/1000/l05lx8w0/poster/i/7/b/medium-poster-movie-titanic-hd-wallpaper-print-poster-on-13x19-original-imagcyczc3wgmnf5.jpeg?q=90"],
      portraitImg:["https://i.pinimg.com/474x/6f/59/72/6f597266f9f2d0a05c49e25ce1e3f749.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/kVrqfYjkTdQ?si=lKFOsd-mROW1KPYC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'James Cameron',
      cast:["Kate Winslet","Leonardo DiCaprio","Billy Zane"],
      price:199,
      release:1997,
      id:4,
      likes:200,
    },
    {
      name:'Silver Linings Playbook',
      category:'Romance,Comedy',
      description:'After being released from a mental institution, Pat meets Tiffany, who suffers from depression. She tells him that she will help him reunite with his wife if he becomes her partner in a competition.',
      landscapeImg:["https://i.ndtvimg.com/mt/movies/2013-02/silverlinings-preoscar.jpg"],
      portraitImg:["https://upload.wikimedia.org/wikipedia/en/9/9a/Silver_Linings_Playbook_Poster.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/kVS-6k2tQAA?si=_L1dVF_L2Rrt1lU_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'David O. Russell',
      cast:["Bradley Cooper","Jennifer Lawrence","Robert De Niro"],
      price:199,
      release:2012,
      id:5,
      likes:30,
    },
    {
      name:'Eternal Sunshine of the Spotless Mind',
      category:'Romance,Sci-fi',
      description:'Joel finds out that his girlfriend, Clementine, has had him erased from her memories and decides to do the same. During the time of the clinical procedure, he realizes that he still loves her deeply.',
      landscapeImg:["https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/55878b0e-946f-45a4-9486-6770d72e0db5/d23xek7-fd654625-0b7c-4d0a-a3e6-ffae219d367a.jpg/v1/fill/w_900,h_563,q_75,strp/alice_in_wonderland_wallpaper_by_tomjg_d23xek7-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTYzIiwicGF0aCI6IlwvZlwvNTU4NzhiMGUtOTQ2Zi00NWE0LTk0ODYtNjc3MGQ3MmUwZGI1XC9kMjN4ZWs3LWZkNjU0NjI1LTBiN2MtNGQwYS1hM2U2LWZmYWUyMTlkMzY3YS5qcGciLCJ3aWR0aCI6Ijw9OTAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.OpKAYTMiyOnpjIUT7IF9VIT6HrTQpQRL7gKYOyq7Dv4"],
      portraitImg:["https://images.squarespace-cdn.com/content/v1/5fea3b3d46d31b1ddd850cf5/1610165727380-8HR12YM76EMVYOK9VEGR/eternalsunshine.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/07-QBnEkgXU?si=zAbABy6ebxrhFLvX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Michel Gondry',
      cast:["Jim Carrey","Kate Winslet","Kirsten Dunst"],
      price:199,
      release:2004,
      id:6,
      likes:12,
    },
    {
      name:'Alice in Wonderland 2010',
      category:'Fantasy,Adventure',
      description:'Alice, now 19 years old, follows a rabbit in a blue coat to a magical wonderland from her dreams where she is reunited with her friends who make her realise her true destiny.',
      landscapeImg:["https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/55878b0e-946f-45a4-9486-6770d72e0db5/d23xek7-fd654625-0b7c-4d0a-a3e6-ffae219d367a.jpg/v1/fill/w_900,h_563,q_75,strp/alice_in_wonderland_wallpaper_by_tomjg_d23xek7-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTYzIiwicGF0aCI6IlwvZlwvNTU4NzhiMGUtOTQ2Zi00NWE0LTk0ODYtNjc3MGQ3MmUwZGI1XC9kMjN4ZWs3LWZkNjU0NjI1LTBiN2MtNGQwYS1hM2U2LWZmYWUyMTlkMzY3YS5qcGciLCJ3aWR0aCI6Ijw9OTAwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.OpKAYTMiyOnpjIUT7IF9VIT6HrTQpQRL7gKYOyq7Dv4"],
      portraitImg:["https://upload.wikimedia.org/wikipedia/en/thumb/3/36/Alice_in_Wonderland_%282010_film%29.png/220px-Alice_in_Wonderland_%282010_film%29.png"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/9POCgSRVvf0?si=T6x3IL3lHEZbVE41" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Tim Burton',
      cast:["Johnny Depp","Mia Wasikowska","Helena Bonham Carter"],
      price:199,
      release:2010,
      id:7,
      likes:32,
    },
    {
      name:'The Shape of Water',
      category:'Romance,Fantasy',
      description:'Elisa, a lonely janitor, stumbles upon an amphibious creature that is held captive in a secret research facility. She then develops a unique relationship with the creature.',
      landscapeImg:["https://m.media-amazon.com/images/S/pv-target-images/e9b4a5eda5b9835037bc93b9129167332d39f664146289528feb31b7d163df35.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BNGNiNWQ5M2MtNGI0OC00MDA2LWI5NzEtMmZiYjVjMDEyOWYzXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/XFYWazblaUA?si=3hXkEkRNX-PwsCwC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Guillermo del Toro',
      cast:["Sally Hawkins","Michael Shannon","Richard Jenkins"],
      price:199,
      release:2017,
      id:8,
      likes:45,
    },
    {
      name:'Fantasy Island',
      category:'Horror,Fantasy',
      description:'A mysterious man invites a group of lucky guests to his secretive resort to fulfil their darkest fantasies. However, when people start arriving, things take an unexpected turn.',
      landscapeImg:["https://parsi-times.com/wp-content/uploads/2020/02/Fantasy-Island_lds.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BOWE2ODZhYWYtNTFiYy00MjdmLWIzZGEtNTkyOTc1NDIwMjk4XkEyXkFqcGdeQXVyMzY0MTE3NzU@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/FDJDujWJhzw?si=R7kOeFZkOTk6J0md" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Jeff Wadlow',
      cast:["Lucy Hale","Michael Peña","Maggie Q"],
      price:199,
      release:2020,
      id:9,
      likes:23,
    },
    {
      name:'Twilight',
      category:'Romance,Fantasy',
      description:'Bella Swan is an average teenager who often goes unnoticed. However, her life changes for the better when she meets Edward Cullen, a vampire with dreamy eyes and skin that sparkles in sunlight.',
      landscapeImg:["https://www.dexerto.com/cdn-cgi/image/width=3840,quality=75,format=auto/https://editors.dexerto.com/wp-content/uploads/2023/06/22/Twilight.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMTQ2NzUxMTAxN15BMl5BanBnXkFtZTcwMzEyMTIwMg@@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/uxjNDE2fMjI?si=XxELLR_8BIvPghpz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Catherine Hardwicke',
      cast:["Kristen Stewart","Robert Pattinson","Peter Facinelli"],
      release:2008,
      id:10,
      likes:104,
    },
    {
      name:'The Hunger Games',
      category:'Action,Sci-fi',
      description:'Katniss volunteers to replace her sister in a tournament that ends only when one participant remains. Pitted against contestants who have trained for this all their life, she has little to rely on.',
      landscapeImg:["https://static1.colliderimages.com/wordpress/wp-content/uploads/2021/12/hunger-games-movies-ranked-social-feature.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMjA4NDg3NzYxMF5BMl5BanBnXkFtZTcwNTgyNzkyNw@@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/mfmrPu43DF8?si=sJJv9gG0QuYTP383" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Gary Ross',
      cast:["Jennifer Lawrence","Josh Hutcherson","Liam Hemsworth"],
      price:199,
      release:2012,
      id:11,
      likes:45,
    },
    {
      name:"Harry Potter and the Philosopher's Stone",
      category:'Fantasy,Adventure',
      description:'Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him.',
      landscapeImg:["https://i0.wp.com/www.unitedbypop.com/wp-content/uploads/2021/11/HP-Philosophers-Stone.jpg?fit=660%2C330&ssl=1"],
      portraitImg:["https://static.wikia.nocookie.net/harrypotter/images/f/fb/PS_poster.jpg/revision/latest?cb=20180318153750"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/mNgwNXKBEW0?si=GSEXgYs1jWPTR3CR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Chris Columbus',
      cast:["Daniel Radcliffe","Rupert Grint","Emma Watson"],
      price:199,
      release:2001,
      id:12,
      likes:89,
    },
    {
      name:'Ghostbusters: Afterlife',
      category:'Comedy,Fantasy',
      description:'A single mother and her two children move into a farmhouse inherited from her estranged father. As they settle in, they discover their associations with Ghostbusters.',
      landscapeImg:["https://m.media-amazon.com/images/S/pv-target-images/d7c9a3d8da181b1630747604407eb7ae8b3754713ea6a0dd07d8a11dd4e6e098.jpg"],
      portraitImg:["https://resizing.flixster.com/c4d-DNKbp8BB0muVB3_-nkbmKZs=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzYwOWNlODJmLTE1OTEtNGNiMi1hZWIxLTc5ZjYwNGQxYWQ4OS5qcGc="],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/ahZFCF--uRY?si=RQYWbvmYuXru2iXM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Jason Reitman',
      cast:["Carrie Coon","Finn Wolfhard","Mckenna Grace"],
      price:199,
      release:2021,
      id:13,
      likes:74,
    },
    {
      name:'Furious 7',
      category:'Action,Adventure',
      description:"Dominic and his family are caught in a quagmire when Shaw's brother seeks bloody revenge. They must not only deal with their enemy but also save a crucial programme from falling into the wrong hands.",
      landscapeImg:["https://i.insider.com/55086532eab8eacc61092d76?width=700"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMTBmNWQ0Y2UtOTQ3Yy00OTZjLWE0MWYtOTk1YWRiNTFlN2EzXkEyXkFqcGdeQXVyMTE5NzI0NDM@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/Skpu5HaVkOc?si=TsQRZ7N1Vou3jDux" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'James Wan',
      cast:["Vin Diesel","Paul Walker","Dwayne Johnson"],
      price:199,
      release:2015,
      id:14,
      likes:320,
    },
    {
      name:'Extraction',
      category:'Action,Thriller',
      description:"While battling his own demons, Tyler, a ruthless mercenary, accepts the offer of rescuing an Indian crime lord's teenage son from Bangladesh. However, when he arrives, a gruesome blood bath ensues.",
      landscapeImg:["https://hips.hearstapps.com/hmg-prod/images/chris-hemsworth-extraction-2-64638a9a936b7.jpg?crop=1.00xw:0.376xh;0,0.0771xh&resize=1200:*"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BNDBkOWNiMTYtMjlkZS00NzJlLTg0ZmUtN2YwYWQ3N2I3N2Y0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/L6P3nI6VnlY?si=UL-4zcqsNMfBACKM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Sam Hargrave',
      cast:["Chris Hemsworth","Rudhraksh Jaiswal","Randeep Hooda"],
      price:199,
      release:2020,
      id:15,
      likes:78,
    },
    {
      name:'Everest',
      category:'Adventure,Thriller',
      description:'Two groups, one led by Rob Hall and the other by Scott Fischer, encounter several challenges and threatening weather conditions as they attempt to scale Mount Everest.',
      landscapeImg:["https://s3.amazonaws.com/static.rogerebert.com/uploads/review/primary_image/reviews/everest-2015/Everest_2015_1.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMTNmMzM0ZTktZWY3Yy00ODViLTllZDgtODcwM2QyM2E2YTU2L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/79Q2rrQlPW4?si=itNdbXKNNfhKqhEQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Baltasar Kormákur',
      cast:["Jason Clarke","Jake Gyllenhaal","Josh Brolin"],
      price:199,
      release:2015,
      id:16,
      likes:111,
    },
    {
      name:'No Escape',
      category:'Action,Thriller',
      description:"Jack Dwyer moves to Southeast Asia with his family and gets caught between a political uprising and riots aimed at foreign companies. However, he decides to face the situation for his family's safety.",
      landscapeImg:["https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p11132509_v_h10_ae.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMjE0MDI3NTE5NF5BMl5BanBnXkFtZTgwNzI3ODM2NjE@._V1_FMjpg_UX1000_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/Y1G66HyiTxM?si=vo8vyaitKmQvyiTE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'John Erick Dowdle',
      cast:["Owen Wilson","Lake Bell","Sterling Jerins"],
      price:199,
      release:2015,
      id:17,
      likes:89,
    },
    {
      name:'Oxygen',
      category:'Sci-fi,Thriller',
      description:'A woman wakes up in a cryogenic chamber with no recollection of how she got there, and she must find a way out before running out of air.',
      landscapeImg:["https://statcdn.fandango.com/MPX/image/NBCU_Fandango/456/539/thumb_00E39CF6-6965-473C-9F7E-2945F29E671C.jpg"],
      portraitImg:["https://upload.wikimedia.org/wikipedia/en/d/de/Oxygen_2021_poster.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/8IqXgZd-P98?si=CncUcT-ZvrS8XncB" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Alexandre Aja',
      cast:["Mélanie Laurent","Mathieu Amalric","Malik Zidi"],
      price:199,
      release:2021,
      id:18,
      likes:84,
    },
    {
      name:'Dune',
      category:'Sci-fi,Adventure',
      description:'Paul Atreides arrives on Arrakis after his father accepts the stewardship of the dangerous planet. However, chaos ensues after a betrayal as forces clash to control melange, a precious resource.',
      landscapeImg:["https://itsmoreofacomment.com/wp-content/uploads/2021/09/Dune-Movie-Official-Poster-banner-feature.jpg"],
      portraitImg:["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvJznVehDbSUPihJbSTNwH8Tgnvh4ZDxs0J4hV06wOvHHidHul"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/8g18jFHCLXk?si=gypxiyS8djpkhb-f" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Denis Villeneuve',
      cast:["Timothée Chalamet","Rebecca Ferguson","Zendaya"],
      price:199,
      release:2021,
      id:19,
      likes:156,
    },
    {
      name:'Bullet Train',
      category:'Action,Comedy',
      description:'Ladybug, a professional assassin, is assigned to retrieve a briefcase from a bullet train. Soon, he finds himself battling many other killers who board the same train but with a different objective.',
      landscapeImg:["https://static.wixstatic.com/media/f9a487_05994e7df2f74205bc13cea445d8aac0~mv2.png/v1/fill/w_640,h_360,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/f9a487_05994e7df2f74205bc13cea445d8aac0~mv2.png"],
      portraitImg:["https://upload.wikimedia.org/wikipedia/en/thumb/1/13/Bullet_Train_%28poster%29.jpeg/220px-Bullet_Train_%28poster%29.jpeg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/0IOsk2Vlc4o?si=ve9HRyPkrf2bN3bP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'David Leitch',
      cast:["Brad Pitt","Joey King","Aaron Taylor-Johnson"],
      price:199,
      release:2022,
      id:20,
      likes:69,
    },
    {
      name:'Joker',
      category:'Thriller,Crime',
      description:'Arthur Fleck, a party clown, leads an impoverished life with his ailing mother. However, when society shuns him and brands him as a freak, he decides to embrace the life of crime and chaos.',
      landscapeImg:["https://namiccns.org/wp-content/uploads/2019/10/mental_health_movie_review_joker.jpg"],
      portraitImg:["https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Joker_%282019_film%29_poster.jpg/220px-Joker_%282019_film%29_poster.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/zAGVQLHvwOY?si=Yv56tYJvP2EWFcwT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Todd Phillips',
      cast:["Joaquin Phoenix","Robert De Niro","Zazie Beetz"],
      price:199,
      release:2019,
      id:21,
      likes:205,
    },
    {
      name:'Prey',
      category:'Action,Sci-fi',
      description:'A skilled Comanche warrior protects her tribe from a highly evolved alien predator that hunts humans for sport, fighting against wilderness, dangerous colonisers and this mysterious creature to keep her people safe.',
      landscapeImg:["https://attractionsmagazine.com/wp-content/uploads/2022/08/Prey-preditor.jpg"],
      portraitImg:["https://resizing.flixster.com/pbJEPbmzbJO7G6_fE7Sij-2rMuY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzYzMjg3YWE5LTMxOGEtNDYyYi1hY2I2LTI1MGZhOGU1MzBkNi5qcGc="],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/wZ7LytagKlc?si=acy7g7rz47yvSTcr" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Dan Trachtenberg',
      cast:["Amber Midthunder","Dane DiLiegro","Michelle Thrush"],
      price:199,
      release:2022,
      id:22,
      likes:145,
    },
    {
      name:'No Hard Feelings',
      category:'Comedy,Drama',
      description:"On the brink of losing her childhood home, a desperate woman agrees to date a wealthy couple's introverted and awkward 19-year-old son. However, he proves to be more of a challenge than she expected, and time is running out before she loses it all.",
      landscapeImg:["https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p23561164_v_h8_ag.jpg"],
      portraitImg:["https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p23561164_v_v13_ag.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/W3-slBOV84w?si=5WkQPs98gjIQTYCE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Gene Stupnitsky',
      cast:["Jennifer Lawrence","Andrew Barth Feldman","Laura Benanti"],
      price:199,
      release:2023,
      id:23,
      likes:45,
    },
    {
      name:'The Hustle',
      category:'Comedy,Drama',
      description:"Two crooks who come from very different backgrounds meet on their way to the French Riviera and decide to join forces and swindle Thomas Westerburg, a billionaire.",
      landscapeImg:["https://m.media-amazon.com/images/S/pv-target-images/d42d1e55e4aae495555f224dbe319c83b4a28784e81e0a6eede8cc8e90e3fdc3.jpg"],
      portraitImg:["https://cdn.moviefone.com/admin-uploads/posters/the-hustle-poster_1552655013.jpg?d=360x540&q=60"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/_j5hwooOHVE?si=sq7mZuBWbjyifD3P" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Chris Addison',
      cast:["Anne Hathaway","Rebel Wilson","Alex Sharp"],
      price:199,
      release:2019,
      id:24,
      likes:25,
    },
    {
      name:'Due Date',
      category:'Comedy,Drama',
      description:"Peter Highman must reach Los Angeles to make it in time for his child's birth. However, he is forced to travel with Ethan, an aspiring actor, who frequently lands him in trouble.",
      landscapeImg:["https://m.media-amazon.com/images/S/pv-target-images/e1b7e77f8947cabc13f0a216e89cec6d3f2d58df112defa48671411f3f3934f0.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMTU5MTgxODM3Nl5BMl5BanBnXkFtZTcwMjMxNDEwNA@@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/1p3NnJ_oiE0?si=63Oozgl6jjf9yyHj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Todd Phillips',
      cast:["Robert Downey Jr.","Zach Galifianakis","Michelle Monaghan"],
      price:199,
      release:2010,
      id:25,
      likes:35,
    },
    {
      name:'Annabelle',
      category:'Horror,Supernatural',
      description:"John and Mia Form are attacked by members of a satanic cult that uses their old doll as a conduit to make their life miserable. This unleashes a string of paranormal events in the Forms' residence.",
      landscapeImg:["https://static01.nyt.com/images/2014/10/03/arts/03ANNABELLE/ANNABELLE-articleLarge.jpg?quality=75&auto=webp&disable=upscale"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BYmI4NDNiMmQtZTFkYi00ZDVmLThlYTAtMWJlMjU1M2I2ZmViXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/paFgQNPGlsg?si=zMVgmbfaxWDcnhLF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'John R. Leonetti',
      cast:["Annabelle Wallis","Ward Horton","Tony Amendola"],
      price:199,
      release:2014,
      id:26,
      likes:255,
    },
    {
      name:'Annabelle: Creation',
      category:'Horror,Drama',
      description:"A doll-maker and his wife embed the spirit of their deceased daughter inside a doll. Years later, a nun and several girls from a shuttered orphanage become victims of the possessed doll, Anabelle.",
      landscapeImg:["https://gcaggiano.files.wordpress.com/2018/09/annabelle-creation-movie-poster.jpg"],
      portraitImg:["https://www.femalefirst.co.uk/image-library/deluxe/a/annabelle-creation-new-poster-deluxe.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/KisPhy7T__Q?si=uJWs9LUDdzfGFNTh" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'David F. Sandberg',
      cast:["Stephanie Sigman","Talitha Bateman","Anthony LaPaglia"],
      price:199,
      release:2017,
      id:27,
      likes:205,
    },
    {
      name:'The Conjuring 2',
      category:'Horror,Suspense',
      description:"Peggy, a single mother of four children, seeks the help of occult investigators Ed and Lorraine Warren when she and her children witness strange, paranormal events in their house.",
      landscapeImg:["https://www.usatoday.com/gcdn/-mm-/4716673bcc6795583cd6fc6c5c7aef32573d796d/c=16-0-2133-1196/local/-/media/2016/06/07/USATODAY/USATODAY/636008972428721080-CON2-FP-168.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BZjU5OWVlN2EtODNlYy00MjhhLWI0MDUtMTA3MmQ5MGMwYTZmXkEyXkFqcGdeQXVyNjE5MTM4MzY@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/VFsmuRPClr4?si=4DjvIRjD6QSjOBBa" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'James Wan',
      cast:["Vera Farmiga","Patrick Wilson","Madison Wolfe"],
      price:199,
      release:2016,
      id:28,
      likes:295,
    },
    {
      name:'Godzilla: King of the Monsters',
      category:'Sci-fi,Action',
      description:"A legendary monster named King Ghidorah awakens Rodan, as well as other titans, to destroy the world. To defeat them, the crypto-zoological organisation Monarch must rely on the almighty Godzilla.",
      landscapeImg:["https://ntvb.tmsimg.com/assets/p13796942_v_h8_ab.jpg?w=1280&h=720"],
      portraitImg:["https://images-na.ssl-images-amazon.com/images/S/pv-target-images/693294e690001066488a33adedb6ac6b2dc8171d41682b6715fdd0df1222af4f._RI_TTW_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/wVDtmouV9kM?si=wg6ATP3ii8xzHdqL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Michael Dougherty',
      cast:["Kyle Chandler","Vera Farmiga","Millie Bobby Brown"],
      price:199,
      release:2019,
      id:29,
      likes:175,
    },
    {
      name:'Pride & Prejudice 2015',
      category:'Romance,Drama',
      description:"Elizabeth Bennett is a strong-willed yet sensible young woman. At a local ball, she encounters a wealthy young man, Mr Fitzwilliam Darcy, who is arrogant, and they develop an unusual relationship.",
      landscapeImg:["https://fellowstreamer.com/wp-content/uploads/2023/02/Pride-and-Prejudece-poster-jpg.webp"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMTA1NDQ3NTcyOTNeQTJeQWpwZ15BbWU3MDA0MzA4MzE@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/Ur_DIHs92NM?si=5_IpvMOQqOZ1WqJl" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Joe Wright',
      cast:["Keira Knightley","Matthew Macfadyen","Carey Mulligan"],
      price:199,
      release:2005,
      id:30,
      likes:71,
    },
    {
      name:'Gifted',
      category:'Drama,Comedy',
      description:"Frank, a single man raising his genius niece, Mary, gets into a legal battle with his mother, Evelyn, over her custody. However, Evelyn will do anything to make Mary complete her mother's project.",
      landscapeImg:["https://rainforestmind.com/wp-content/uploads/2017/04/gifted-movie-poster.jpg?w=300"],
      portraitImg:["https://musicart.xboxlive.com/7/5cc44400-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/x7CAjpdRaXU?si=xu8ViGB3K0Fu7OSv" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Marc Webb',
      cast:["Mckenna Grace","Chris Evans","Jenny Slate"],
      price:199,
      release:2017,
      id:31,
      likes:161,
    },
    {
      name:'Tick, Tick... Boom!',
      category:'Musical,Drama',
      description:"Based on the autobiographical musical by playwright Jonathan Larson. It's the story of an aspiring composer in New York City who is worried he made the wrong career choice, whilst navigating the pressures of love and friendship.",
      landscapeImg:["https://occ-0-2794-993.1.nflxso.net/dnm/api/v6/6gmvu2hxdfnQ55LZZjyzYR4kzGk/AAAABZBXWoeD1zEH3_gX-fZYAJCKMXeIZZQWsN5lt4mR76vA3phYT_9RsEtHVtWRRZvcIIYNp2jz1tRaWxqSoxKNKyJHKBC8SsOdTpBDpV0Gs6Snd5edDuR7o-RMTOaYj3GrZhhqDQ.jpg?r=4ef"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BZmMyMmE0M2UtN2E2MC00YzVmLTkwODgtOTVhYjVlOTBhY2RjXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/YJserno8tyU?si=jf-N6A0dt7fR2Hfk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Lin-Manuel Miranda',
      cast:["Andrew Garfield","Alexandra Shipp","Robin de Jesús"],
      price:199,
      release:2021,
      id:32,
      likes:49,
    },
    {
      name:'West Side Story',
      category:'Musical,Romance',
      description:"Tony, a young man affiliated with a Caucasian gang, meets and falls in love with Maria, the sister of a Puerto Rican gangster. As a result, they face many challenges in their quest to unite.",
      landscapeImg:["https://mickeyblog.com/wp-content/uploads/2021/11/West-Side-Story-poster-720x340.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BMzQ5ZDZhZDItZTNmZi00MWQ0LWJlNDUtZTE4ZWJmODNlM2Y3XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/YJserno8tyU?si=jf-N6A0dt7fR2Hfk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Steven Spielberg',
      cast:["Ansel Elgort","Rachel Zegler","Ariana DeBose"],
      price:199,
      release:2021,
      id:33,
      likes:79,
    },
    {
      name:'A Star is Born',
      category:'Musical,Romance',
      description:"After falling in love with struggling artist Ally, Jackson, a musician, coaxes her to follow her dreams, while he battles with alcoholism and his personal demons.",
      landscapeImg:["https://youthjournalism.org/wp-content/uploads/2019/02/Movie-poster-Star-is-born.jpg"],
      portraitImg:["https://m.media-amazon.com/images/M/MV5BNmE5ZmE3OGItNTdlNC00YmMxLWEzNjctYzAwOGQ5ODg0OTI0XkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/nSbzyEJ8X9E?si=gZOL62kqxbEQQrAL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Bradley Cooper',
      cast:["Lady Gaga","Bradley Cooper","Sam Elliott"],
      price:199,
      release:2018,
      id:34,
      likes:129,
    },
    {
      name:'A Quiet Place',
      category:'Horror,Sci-fi',
      description:"A family lives in a world inhabited by blind but sound sensitive creatures who are out to kill people. In order to survive, they are forced to use the sign language to communicate with each other.",
      landscapeImg:["https://wallpapercave.com/wp/wp2433228.jpg"],
      portraitImg:["https://www.film.nl/img.php?width=800&image=/content/bindinc/e5/e579b00894beebf2c3095532ce35fb3e.jpg"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/WR7cc5t7tv8?si=nNqY0Oc5JJIoi5_c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'John Krasinski',
      cast:["Emily Blunt","John Krasinski","Noah Jupe"],
      price:199,
      release:2018,
      id:35,
      likes:159,
    },
    {
      name:'The Nun II',
      category:'Horror,Mystery',
      description:"In 1956 France, a priest is violently murdered, and Sister Irene begins to investigate. She once again comes face-to-face with a powerful evil.",
      landscapeImg:["https://staticg.sportskeeda.com/editor/2023/09/424b3-16939249177249-1920.jpg"],
      portraitImg:["https://cdn.cinematerial.com/p/297x/xnnocoqf/the-nun-ii-movie-poster-md.jpg?v=1692433122"],
      trailer:'<iframe width="560" height="315" src="https://www.youtube.com/embed/QF-oyCwaArU?si=NgcvEcC-bpKvliP0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
      director:'Michael Chaves',
      cast:["Taissa Farmiga","Jonas Bloquet","Storm Reid"],
      price:199,
      release:2023,
      id:36,
      likes:209,
    }
]

export const cart = [
//   {
//     title:'kick',
//     category:'Action',
//     img:'/icons/netflix.png',
//     price:499,
//     date:'21/10/2023',
//     style:' flex items-center justify-between '
//  }
]

export const wishlist = [
  {
    title:'Thara',
    category:'Revenge',
    img:'/icons/netflix.png',
    price:499,
    date:'11/06/2023',
    style:' flex items-center justify-between '
 }
]